apiVersion: apps/v1
kind: Deployment
metadata:
  name: math-homework-pdf-gen-deployment
  labels:
    app: math-homework-pdf-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: math-homework-pdf-gen
  template:
    metadata:
      labels:
        app: math-homework-pdf-gen
    spec:
      containers:
      - name: math-homework-pdf-gen-container
        image: zicongmei/math-homework-pdf-gen:latest # This uses the default IMAGE_REPO and IMAGE_TAG from Makefile
        ports:
        - containerPort: 8080 # This is the CONTAINER_PORT from Makefile
        # Optional: Add readiness and liveness probes if your application supports health check endpoints
        # readinessProbe:
        #   httpGet:
        #     path: /health # Replace with your actual health check endpoint
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        # livenessProbe:
        #   httpGet:
        #     path: /health # Replace with your actual health check endpoint
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        resources: # Optional: Define resource requests and limits
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: math-homework-pdf-gen-lb-service
  labels:
    app: math-homework-pdf-gen
spec:
  type: LoadBalancer
  selector:
    app: math-homework-pdf-gen # This must match the labels of the pods managed by the Deployment
  ports:
    - protocol: TCP
      port: 80 # The port the service will be exposed on externally by the LoadBalancer
      targetPort: 8080 # The port on the pods (containerPort) that the service will forward traffic to